language: php

php:
  - 7.0

before_install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml


install:
  - composer self-update
  - composer install

script:
  - make build

after_script:
  - vendor/bin/test-reporter
