AppBundle\Entity\CommentDto:
  type: entity
  table: comment
  repositoryClass: AppBundle\Repository\Doctrine\DoctrineCommentRepository
  indexes:
    - columns: [post_id]
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    postId:
      type: integer
    content:
      type: text
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    active:
      type: boolean
  manyToOne:
    author:
      targetEntity: AppBundle\Entity\Author
      fetch: EAGER
      cascade: [persist]
      joinColumn:
        name: author_id
        referencedColumnName: id
        nullable: false
  manyToMany:
    mentions:
      targetEntity: AppBundle\Entity\Mention
      cascade: [persist]
      orphanRemoval: true
      joinTable:
        name: comment_to_mention
        joinColumns:
          comment_id:
            referencedColumnName: id
        inverseJoinColumns:
          mention_id:
            referencedColumnName: id
