AppBundle\Entity\Comment:
  type: entity
  table: comment
  repositoryClass: AppBundle\Repository\Doctrine\DoctrineCommentRepository
  indexes:
    - columns: [post_id]
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    postId:
      type: integer
    content:
      type: text
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    active:
      type: boolean
  manyToOne:
    author:
      targetEntity: AppBundle\Entity\Author
      fetch: EAGER
      joinColumn:
        name: author_id
        referencedColumnName: user_id
        nullable: false
  oneToMany:
    mentions:
      targetEntity: AppBundle\Entity\Mention
      cascade: [persist]
      mappedBy: comment
      orphanRemoval: true
