Foodlove\AppBundle\Entity\Mention:
  type: entity
  table: mention
  repositoryClass: Foodlove\AppBundle\Repository\Doctrine\DoctrineMentionRepository
  uniqueConstraints:
    - columns: [user_id]
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    userId:
      type: integer
    username:
      type: string
      length: 255
