AppBundle\Entity\Mention:
  type: entity
  table: mention
  repositoryClass: AppBundle\Repository\Doctrine\DoctrineMentionRepository
  uniqueConstraints:
    - columns: [comment_id, user_id]
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    author:
      type: integer
  manyToOne:
    comment:
      targetEntity: AppBundle\Entity\Comment
      inversedBy: mentions
      joinColumn:
        name: comment_id
        referencedColumnName: id
        nullable: false
