<?php

namespace AppBundle\Repository;

/**
 * MentionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionRepository extends \Doctrine\ORM\EntityRepository
{
}
