parameters:
  avatar.default_avatar: "/assets/img/default_avatar.png"
  avatar.upload_path: "/uploads/avatars"

services:
  comments.controller.list:
    class: AppBundle\Controller\Comments\ListController
    arguments:
      - "@comments.repository.comment"
      - "@comments.mapper.entity_to_dto.comment"
  comments.controller.create:
    class: AppBundle\Controller\Comments\CreateController
  comments.controller.remove:
    class: AppBundle\Controller\Comments\RemoveController

  comments.repository.comment:
    class: AppBundle\Repository\CommentRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Comment
  comments.repository.mention:
    class: AppBundle\Repository\MentionRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Mention

  comments.mapper.entity_to_dto.comment:
    class: AppBundle\Mapper\EntityToDto\CommentMapper
    arguments:
      - "@comments.upload_path_resolver.avatar"

  comments.configuration_fetcher.local:
    class: AppBundle\Service\ConfigurationFetcher\LocalConfigurationFetcher
    calls:
      - [setParameterBag, ["@=service('service_container').getParameterBag()"]]

  comments.upload_path_resolver.avatar:
    class: AppBundle\Service\UploadPathResolver\Avatar\AvatarUploadPathResolver
    arguments:
      - "@comments.configuration_fetcher.local"
