parameters:
  avatar.default_avatar: "/assets/img/default_avatar.png"
  avatar.upload_path: "/uploads/avatars"

services:
  comments.listener.timestampable:
    class: Gedmo\Timestampable\TimestampableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  comments.controller.list:
    class: Foodlove\AppBundle\Controller\Comments\ListController
    arguments:
      - "@comments.response.factory.dto"
      - "@comments.repository.comment"
      - "@comments.mapper.entity_to_dto.comment"
  comments.controller.create:
    class: Foodlove\AppBundle\Controller\Comments\CreateController
    arguments:
      - "@comments.response.factory.dto"
      - "@serializer"
      - "@comments.mapper.dto_to_entity.comment"
      - "@comments.repository.comment"
      - "@comments.mapper.entity_to_dto.comment"
      - "@comments.validator.handler.create_comment"
  comments.controller.remove:
    class: Foodlove\AppBundle\Controller\Comments\RemoveController
    arguments:
      - "@comments.repository.comment"

  comments.repository.comment:
    class: Foodlove\AppBundle\Repository\CommentRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - Foodlove\AppBundle\Entity\Comment
  comments.repository.mention:
    class: Foodlove\AppBundle\Repository\MentionRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - Foodlove\AppBundle\Entity\Mention
  comments.repository.author:
    class: Foodlove\AppBundle\Repository\AuthorRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - Foodlove\AppBundle\Entity\Author

  comments.mapper.entity_to_dto.comment:
    class: Foodlove\AppBundle\Mapper\EntityToDto\CommentMapper
    arguments:
      - "@comments.upload_path_resolver.avatar"

  comments.mapper.dto_to_entity.comment:
    class: Foodlove\AppBundle\Mapper\DtoToEntity\CommentMapper
    arguments:
      - "@comments.repository.author"

  comments.configuration_fetcher.local:
    class: Foodlove\AppBundle\Service\ConfigurationFetcher\LocalConfigurationFetcher
    calls:
      - [setParameterBag, ["@=service('service_container').getParameterBag()"]]

  comments.upload_path_resolver.avatar:
    class: Foodlove\AppBundle\Service\UploadPathResolver\Avatar\AvatarUploadPathResolver
    arguments:
      - "@comments.configuration_fetcher.local"

  comments.response.factory.dto:
    class: Foodlove\AppBundle\Service\ResponseFactory\DtoResponseFactory
    arguments:
      - "@serializer"

  comments.serializer.yaml_config_loader:
    class: Symfony\Component\Serializer\Mapping\Loader\YamlFileLoader
    arguments:
      - "%kernel.root_dir%/config/serializer.yml"
  comments.serializer.class_metadata_factory:
    class: Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory
    arguments:
      - "@comments.serializer.yaml_config_loader"
  comments.serializer.object_normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      - "@comments.serializer.class_metadata_factory"
      - "@serializer.name_converter.camel_case_to_snake_case"
    tags:
      - { name: serializer.normalizer }

  comments.validator:
    class: Symfony\Component\Validator\Validator\ValidatorInterface
    factory: ["@comments.validator.builder", getValidator]
  comments.validator.builder:
    parent: validator.builder
    calls:
      - [addYamlMapping, ["%kernel.root_dir%/config/validation.yml"]]
  comments.validator.handler.create_comment:
    class: Foodlove\AppBundle\Service\Validator\Handler\CreateCommentHandler
    arguments:
      - "@comments.validator"
